name: Execute go.sh

on:
    push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Execute Script
        run: source go.sh | tee result.txt

      - name: Save result as file
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: result.txt
